<?php
// $Id: search_files.module,v 1.19.2.12 2009/08/15 17:18:54 thl Exp $

/**
 * @file
 * Used to index all files in directory(s) on the server
 */

/**
 * Implementation of hook_menu().
 *
 * @return $items = array of menu items
 */
function search_files_menu() {
  $items = array();
  $items['admin/settings/search_files'] = array(
    'title' => t('Search Files'),
    'description' => t('Manage files search'),
    'page callback' => 'search_files_dashboard',
    'access arguments' => array('administer search_files configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/settings/search_files/dashboard'] = array(
    'title' => t('Dashboard'),
    'description' => t('Dashboard for Search Files Module'),
    'page callback' => 'search_files_dashboard',
    'access arguments' => array('administer search_files configuration'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/settings/search_files/helpers'] = array(
    'title' => t('Helpers'),
    'description' => t('List Helper Apps for Search Files'),
    'page callback' => 'search_files_helper_list',
    'access arguments' => array('administer search_files configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/settings/search_files/helpers/list'] = array(
    'title' => t('List'),
    'description' => t('List Helper Apps for Search Files'),
    'page callback' => 'search_files_helper_list',
    'access arguments' => array('administer search_files configuration'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/settings/search_files/helpers/add'] = array(
    'title' => t('Add'),
    'description' => t('Add Helper Apps for Search Files'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('search_files_helper_add'),
    'access arguments' => array('administer search_files configuration'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/settings/search_files/helpers/edit'] = array(
    'title' => t('Edit Helper'),
    'description' => t('Edit a Helper App'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('search_files_helper_edit'),
    'access arguments' => array('administer search_files configuration'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/search_files/helpers/delete'] = array(
    'title' => t('Delete Helper'),
    'description' => t('Delete a Helper App'),
    'page callback' => 'search_files_helper_confirm_delete',
    'access arguments' => array('administer search_files configuration'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * generate the dashboard page
 */
function search_files_dashboard() {
  $output = '';
  $lastindex = variable_get('search_files_directories_last_index', 0);
  if ($lastindex == 0) {
    $output .= sprintf("%s = <i>%s</i><br/>\n", t('Last Index'), t('never'));
  }
  else {
    $output .= sprintf("%s = %s UTC<br/>\n", t('Last Index'),
      format_date($lastindex, $type = 'custom', $format = 'Y-m-d H:i:s', $timezone = NULL, $langcode = NULL));
  }

  $directoryrescanage = search_files_variable_get_directoryrescanage();
  $output .= sprintf("%s = %s [sec]<br/>\n", t('Directory Rescan Age'), $directoryrescanage);

  $nextdirectoryrescan = $lastindex + $directoryrescanage;
  $output .= sprintf("%s = %s UTC<br/>\n", t('Next Directory (Re-)Scan at or after'),
    format_date($nextdirectoryrescan, $type = 'custom', $format = 'Y-m-d H:i:s', $timezone = NULL, $langcode = NULL));

  $sql = "SELECT count(*) FROM {search_files_directories};";
  $result = db_query($sql);
  $result = db_result($result);
  $output .= sprintf("Number of Directories configured = %s<br/>\n", $result);

  $sql = "SELECT count(*) FROM {search_files_directories_files};";
  $result = db_query($sql);
  $result = db_result($result);
  $output .= sprintf("Files found in configured Directories and Subdirectories = %s<br/>\n", $result);

  $sql = "SELECT count(*) FROM {search_files_directories_files} WHERE `index_attempts` = 0;";
  $result = db_query($sql);
  $result = db_result($result);
  $output .= sprintf("Files without index attempt = %s<br/>\n", $result);

  $sql = "SELECT count(*) FROM {search_dataset} WHERE `type` = 'search_files';";
  $result = db_query($sql);
  $result = db_result($result);
  $output .= sprintf("Files indexed = %s<br/>\n", $result);

  $sql = "SELECT count(*) FROM {search_dataset} WHERE (`type` = 'search_files' AND `reindex` > 0);";
  $result = db_query($sql);
  $result = db_result($result);
  $output .= sprintf("Files indexed and scheduled for reindexing = %s<br/>\n", $result);

  $sql = "SELECT count(*) FROM {search_files_helpers};";
  $result = db_query($sql);
  $result = db_result($result);
  $output .= sprintf("Number of Helpers configured = %s<br/>\n", $result);

  // safe_mode will inhibit shell_exec()
  if (search_files_issafemode()) {
    $output .= t('<b>WARNING!</b> This server has safe_mode enabled, which inhibits use of helper applications');
  }
  else {
    $output .= t('Good. This server has safe_mode disabled, which allows use of helper applications');
  }

  return $output;
}

/**
 * get an array of helper programs
 *
 * @return $helpers = array($helper->extension => $helper->helper_path);
 */
function search_files_get_helpers() {
  // Get all the registered helper applications and put them in static variable to elimiate unnecessary db queries
  // in search_files_nodeapi(). The query log feature of the dev module pointed out that this query was done
  // many times instead of once. Making $helpers a static variable reduced the number of queries by 25%.
  static $helpers;
  if (! isset($helpers)) {
    $helpers = array();
    $result = db_query("SELECT * FROM {search_files_helpers};");
    while ($helper = db_fetch_object($result)) {
      $helpers[$helper->extension] = $helper->helper_path;
    }
  }
  return $helpers;
}

/**
 * Check whether we run in PHP safe_mode
 */
function search_files_issafemode() {
  return preg_match('/(1|on)/i', @ini_get("safe_mode"));
}

/**
 * check to make sure the $helper_id is valid (a number greater
 * than zero) then it fetches the deletion confirmation form,
 * then returns it
 *
 * @return (array) $form
 */
function search_files_helper_confirm_delete() {
  $helper_id = arg(5);
  if ($helper_id > 0 && is_numeric($helper_id)) {
    return drupal_get_form('search_files_helper_confirm_delete_form', $helper_id);
  }
}

/**
 * generate the deletion confirmation form for helper apps and return the form
 *
 * @param unknown_type $form_state
 * @param (int) $helper_id
 * @return (array) $form
 */
function search_files_helper_confirm_delete_form(&$form_state, $helper_id) {
  $helper_name = db_result(db_query("SELECT name FROM {search_files_helpers} WHERE `id` = %d;", $helper_id));
  $form = array();
  $form['search_files_helper_id'] = array(
    '#type' => 'hidden',
    '#value' => $helper_id
  );
  $form['search_files_helper_name'] = array(
    '#type' => 'hidden',
    '#value' => $helper_name,
  );
  return confirm_form($form,
    t('Are you sure you want to delete the %name helper? The text extracted by this helper will remain in the search index until the directory is reindexed.', array('%name' => $helper_name)),
    'admin/settings/search_files/helpers/list',
    t('This action cannot be undone.'),
    t('Delete'),
    t('Cancel'));
}

/**
 * remove row for the helper app from the search_files_helpers table
 */
function search_files_helper_confirm_delete_form_submit($form, &$form_state) {
  $result = db_query("DELETE FROM {search_files_helpers} WHERE `id` = %d;", $form_state['values']['search_files_helper_id']);
  drupal_goto('admin/settings/search_files/helpers/list');
}
/**
 * display a themes table of the current helper apps set up in the system
 *
 * @return (string) html table
 */
function search_files_helper_list() {
  $output = '';
  $sql = "
    SELECT *
    FROM {search_files_helpers}
    ORDER BY `extension`;
  ";
  $result = db_query($sql);
  $helpers[] = array();
  $destination = drupal_get_destination();
  while ($helper = db_fetch_object($result)) {
    $helpers[] = array($helper->name, $helper->extension, l(t('Edit'), 'admin/settings/search_files/helpers/edit/'. $helper->id), l(t('Delete'), 'admin/settings/search_files/helpers/delete/'. $helper->id), array($destination));
  }
  $header = array(t('Helper name'), t('Extension'), array('data' => t('Operations'), 'colspan' => '3'));
  $output .= theme('table', $header, $helpers);
  return $output;
}

/**
 * Implementation of hook_perm().
 *
 * @return (array) permissions
 */
function search_files_perm() {
    return array('administer search_files configuration', 'view search_files results');
}

/**
 * generate form to add a helper app to the system
 *
 * @return (array) $form
 */
function search_files_helper_add() {
  $form['instructions'] = array('#type' => 'markup', '#value' => $instruction_text);
  $form['search_files_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Helper name'),
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
    '#description' =>  t('A name for this helper configuration.'),
  );
  $form['search_files_extension'] = array(
    '#type' => 'textfield',
    '#title' => t('Extension'),
    '#size' => 10,
    '#maxlength' => 10,
    '#required' => TRUE,
    '#description' =>  t('Enter the extension for the files that you want the helper application to process. Do not include the period.'),
  );
  $form['search_files_helper_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Helper path'),
    '#size' => 100,
    '#maxlength' => 100,
    '#default_value' => '/path/to/helper/command %file%',
    '#validate' => array('search_files_helpers_validate_add_edit' => array()),
    '#required' => TRUE,
    '#description' => t('Enter the path to the helper application installed on your server. "%file%" is a placeholder for the path of the attachment file and is required. Include any command-line parameters as well (for example, pdftotext requires a - after the file to be processed).'),
  );
  $form['submit_done'] = array(
    '#type' => 'submit',
    '#value' => 'Save and Done',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save add another',
  );
  return $form;
}

/**
 * validate the existance of the helper app supplied by the
 * helper_add or helper_edit form
 *
 * @param unknown_type $field
 */
function search_files_helpers_validate_add_edit($field) {
  if (!preg_match('/%file%/', $field['#value'])) {
    form_set_error($field['#title'], t('"%field" must contain the token %file%', array('%field' => $field['#title'])));
  }

  // Check to see if helper app can be found
  $helper_file = preg_replace('/\s.+$/', '', $field['#value']);
  if (!file_exists($helper_file)) {
    form_set_error($field['#title'], t("Can't find helper app %helper -- please verify it is installed.", array('%helper' => $helper_file)));
  }
}

/**
 * fetch the helper add form, alter the form for use as an edit form,
 * populate the #default_values fields and return the form
 *
 * @return unknown
 */
function search_files_helper_edit() {
  $sql = "
    SELECT *
    FROM {search_files_helpers}
    WHERE `id` = %d;
  ";
  $result = db_fetch_object(db_query($sql, arg(5)));
  $form = search_files_helper_add();
  $form['search_file_id'] = array(
    '#type' => 'value',
    '#value' => $result->id,
  );
  $form['search_files_helper_path']['#value'] = $result->helper_path;
  $form['search_files_extension']['#value'] = $result->extension;
  $form['search_files_name']['#value']= $result->name;
  unset($form['submit_done']);
  $form['submit']['#value'] = 'Update';
  return $form;
}

/**
 * update the row in the table search_files_helpers for the given helper app
 */
function search_files_helper_edit_submit($form, &$form_state) {
  $sql = "
    UPDATE {search_files_helpers}
    SET
      `name` = '%s',
      `extension` = '%s',
      `helper_path` = '%s'
    WHERE `id` = %d;
  ";
  $result = db_query($sql, $form_state['clicked_button']['#post']['search_files_name'], $form_state['clicked_button']['#post']['search_files_extension'], $form_state['clicked_button']['#post']['search_files_helper_path'], $form_state['values']['search_file_id']);
  if ($result) {
    drupal_set_message(t('Helper app %helper_name has been updated', array('%helper_name' => $form_state['values']['search_files_name'])));
    drupal_goto('admin/settings/search_files/helpers/list');
  }
}

/**
 * insert a row in the search_files_helpers table for the helper
 * app given by the form
 */
function search_files_helper_add_submit($form, $form_state) {
  $sql = "
    INSERT INTO {search_files_helpers}
    SET
      `name` = '%s',
      `extension` = '%s',
      `helper_path` = '%s';
  ";
  $result = db_query($sql, $form_state['values']['search_files_name'], $form_state['values']['search_files_extension'], $form_state['values']['search_files_helper_path']);
  if ($result) {
    drupal_set_message(t('%helper helper added', array('%helper' => $form_state['values']['search_files_name'])));
  }
  if ($form_state['clicked_button']['#id'] == 'edit-submit-done') {
    drupal_goto('admin/settings/search_files/helpers/list');
  }
}

/**
 * Get the host system's character encoding and convert text from it to UTF-8,
 * Drupal's default HTTP and database character encoding.
 */
function search_files_convert_to_utf8($text) {
  $encoding = iconv_get_encoding("output_encoding");
  $text = drupal_convert_to_utf8($text, $encoding);
  return $text;
}

/**
 * format the result items before that are displayed
 *
 * @param (array) $item
 * @param (string) $type
 * @return (string) $output formatted string
 */
function search_files_search_item_format($item, $type) {
  //drupal_set_message('entry = <pre>'.var_export($item, true).'</pre>');
  $output = ' <dt class="title"><a href="'. check_url($item['link']) .'">'. check_plain($item['title']) .'</a></dt>';
  $info = array();
  if ($item['type']) {
    $info[] = check_plain($item['type']);
  }
  if ($item['user']) {
    // Add this here so the user name appears at the end of the output
    $item['extra'][] = $item['user'];
  }
  if ($item['date']) {
    $info[] = format_date($item['date'], 'small');
  }
  if (is_array($item['extra'])) {
    $info = array_merge($info, $item['extra']);
  }
  $output .= ' <dd>'. ($item['snippet'] ? '<p>'. $item['snippet'] .'</p>' : '') .'<p class="search-info">'. implode(' - ', $info) .'</p></dd>';
  return $output;
}

/**
 * returns an array of the file extensions with the extension as
 * the key and the name of the file type as the value, this data
 * is retrieved from the search_files_helpers table
 *
 * @return (array)
 */
function search_files_get_file_extensions() {
  $extensions = array();
  $result = db_query("SELECT extension, name FROM {search_files_helpers};");
  while ($helper = db_fetch_object($result)) {
    $extensions[$helper->extension] = $helper->name;
  }
  return $extensions;
}
/**
 * Get the name of a helper for the given extension.
 */
function search_files_helper_name($ext) {
  $result = db_query("SELECT name FROM {search_files_helpers} WHERE `extension` = '%s';", $ext);
  if ($helper = db_fetch_object($result)) {
    return $helper->name;
  }
}


function search_files_settings() {
  return '';
}
